language: python

python:
# python versions
- "3.8"
- "3.7"
- "3.6"

# install dependencies
install:
- pip install -r requirements.txt
- pip install django-crispy-forms
- pip install coveralls


script:
-coverage erase
-coverage run --source=./ manage.py test CodeGrinders


after_success:
-coverage report
 coveralls


