language: python

python:
- "3.8"
- "3.7"
- "3.6"


# install dependencies
install:
- pip install -r requirements.txt
- pip install django-crispy-forms

# run test scripts
script:

- python manage.py test
